drop table if exists public.payment_intents cascade;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, company_name text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.profiles enable row level security;
create table if not exists public.accounts (id uuid primary key default gen_random_uuid(), owner_user_id uuid not null references auth.users(id) on delete cascade, name text not null default 'Personal account', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.account_members (account_id uuid not null references public.accounts(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null default 'owner' check (role in ('owner','admin','member')), created_at timestamptz not null default now(), primary key (account_id,user_id));
create table if not exists public.platform_connections (id uuid primary key default gen_random_uuid(), account_id uuid not null references public.accounts(id) on delete cascade, platform text not null, status text not null default 'active' check (status in ('active','reauth_required','disabled')), display_name text, credentials_ref text, metadata jsonb not null default '{}'::jsonb, last_synced_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.financial_accounts add column if not exists account_id uuid references public.accounts(id) on delete cascade;
alter table public.financial_accounts add column if not exists connection_id uuid references public.platform_connections(id) on delete set null;
alter table public.financial_accounts add column if not exists external_id text;
alter table public.financial_accounts add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table public.financial_accounts add column if not exists last_synced_at timestamptz;
create index if not exists accounts_owner_user_id_idx on public.accounts(owner_user_id);
create index if not exists platform_connections_account_id_idx on public.platform_connections(account_id);
create index if not exists financial_accounts_account_id_idx on public.financial_accounts(account_id);
create unique index if not exists financial_accounts_connection_external_id_idx on public.financial_accounts(connection_id,external_id) where external_id is not null;
alter table public.accounts enable row level security;
alter table public.account_members enable row level security;
alter table public.platform_connections enable row level security;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ declare new_account_id uuid; begin insert into public.profiles(id,full_name,company_name) values(new.id,new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'company_name') on conflict(id) do nothing; insert into public.accounts(owner_user_id,name) values(new.id,coalesce(nullif(new.raw_user_meta_data->>'company_name',''),'Personal account')) returning id into new_account_id; insert into public.account_members(account_id,user_id,role) values(new_account_id,new.id,'owner') on conflict do nothing; return new; end; $$;
